### ISSUE TITLE
limit number of parallel builds

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/osbs#85] opened 2015-05-20 12:32 UTC
openshift should help us with this somehow

suggested by @goldmann

@csrwng is there a way to limit number of parallel builds in openshift?

**Comment by goldmann** [comment] 2015-05-20 12:46
Just to clarify: the limit really depends on the HW of the machine and is related to parallel builds that share **the same** Docker daemon. Since daemon is single thread - it has issues replying to the `/images/ID/get` in timely manner, hitting the timeout.

**Comment by csrwng** [comment] 2015-05-20 14:00
@bparees @smarterclatyon - maybe this can be accomplished by specifying ResourceRequirements on the build pods so the scheduler can wait to schedule a build until resources are available. Thoughts?

**Comment by smarterclayton** [comment] 2015-05-20 14:04
That's probably the best way to limit today.  

----- Original Message -----

**Comment by csrwng** [comment] 2015-05-20 14:07
Next question is ... what should those ResourceRequirements be? :)

**Comment by csrwng** [comment] 2015-05-20 14:12
What I mean is that builds are likely to have different resource requirements based on the type, repository, etc. Should we allow configuring them per build/buildConfig?

**Comment by bparees** [comment] 2015-05-20 14:14
we do support that today, derek added it:
https://github.com/openshift/origin/blob/master/pkg/build/api/v1beta3/types.go#L42

**Comment by csrwng** [comment] 2015-05-20 14:16
nice... so all @TomasTomecek needs to do is to add that to his build json. That's easy :)

**Comment by TomasTomecek** [comment] 2015-05-20 17:26
Sweet!

@bparees @smarterclayton Thanks guys!

@csrwng Cesar, could you please provide a sample json? I can't read go that well.

**Comment by twaugh** [comment] 2015-06-11 16:31
There are [examples at github.com/GoogleCloudPlatform/kubernetes](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/resourcequota).

**Comment by twaugh** [comment] 2015-06-17 11:36
So, I have this working locally with only configuration changes.

I created a namespace `singlefile`:

```
# cat namespace.yml
apiVersion: v1
kind: Namespace
metadata:
  name: singlefile
# osc --create -f namespace.yml
```

and set a quota for the number of pods:

```
# cat quota.yml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    pods: 1
# osc --namespace=singlefile create -f quota.yml
```

Now when submitting builds with `osbs --namespace=singlefile ...` only one build goes through at a time. Obviously, we'd configure this to be a larger number in production.

```
# osc --namespace=singlefile get quota
NAME
quota
# osc --namespace=singlefile describe quota quota
Name:		quota
Resource	Used	Hard
--------	----	----
pods		1	1
# osc --namespace=singlefile get builds
NAME                    TYPE      STATUS     POD
test1-20150617-122643   Custom    Running    test1-20150617-122643
test2-20150617-122648   Custom    New        test2-20150617-122648
test3-20150617-122650   Custom    New        test3-20150617-122650
test4-20150617-122652   Custom    New        test4-20150617-122652
test5-20150617-122653   Custom    New        test5-20150617-122653
# osc --namespace=singlefile describe build test5-20150617-122653
[...]
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath	Reason		Message
  Wed, 17 Jun 2015 12:26:53 +0100	Wed, 17 Jun 2015 12:27:31 +0100	2	{build-controller }			failedCreate	Error creating: Pod "test5-20150617-122653" is forbidden: Limited to 1 pods
```

Eventually they all complete:

```
# osc --namespace=singlefile get builds
NAME                    TYPE      STATUS     POD
test1-20150617-122643   Custom    Complete   test1-20150617-122643
test2-20150617-122648   Custom    Complete   test2-20150617-122648
test3-20150617-122650   Custom    Complete   test3-20150617-122650
test4-20150617-122652   Custom    Complete   test4-20150617-122652
test5-20150617-122653   Custom    Complete   test5-20150617-122653
```

although it does seem to take a minute or so to start up a new pod once the resource is freed up, and they don't necessarily start in the order of build submission.

**Comment by twaugh** [comment] 2015-06-17 17:10
I'm having less success using CPU/memory limits. You can see work in progress on the `85-resource-limits` branch.

Setting quota like this:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    memory: 512Mi
    cpu: 200m
```

and submitting builds with `--memory-limit 240Mi --cpu-limit 20m` only allows the first build through. It seems as though completed builds are counting towards used quota, and possibly even after they are deleted:
```
# osc --namespace=restricted get builds
NAME      TYPE      STATUS    POD
# osc --namespace=restricted describe quota quota
Name:		quota
Resource	Used		Hard
--------	----		----
cpu		20m		200m
memory		251658240	512Mi
```

**Comment by csrwng** [comment] 2015-06-17 17:16
@derekwaynecarr ^^

**Comment by derekwaynecarr** [comment] 2015-06-17 17:52
Your quota usage is incremented upon admission of a pod today.
Your quota usage is decremented via a background task that runs every 10s.

That background task filters out pods that are succeeded or failed here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/resourcequota/resource_quota_controller.go#L150

To see what pods are using what resources, you would need to look at the ```osc get pods -o yaml``` output right now.  There is a fix upstream that shows resource limits in a describe call but that has not yet merged.

If your pod has a restart policy, it is included in quota calculations, are we sure that is not the case?

**Comment by twaugh** [comment] 2015-06-17 21:56
Aha, thanks for the `-o yaml` tip. Thanks to that I tracked down a 'pending' pod that was the cause of the used resources.

**Closed** 2015-06-18 07:54 UTC
